version: "3.9"

services:
  pgvector-dashboard:
    build: .
    container_name: pgvector_dashboard
    ports:
      - "8501:8501"
    environment:
      DB_NAME: raise
      DB_TABLE: embeddings
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
    restart: unless-stopped
