version: "3.9"

services:
  pgvector-dashboard:
    build: .
    container_name: pgvector_dashboard
    ports:
      - "8501:8501"
    environment:
      db_name: raise
      db_user: postgres
      db_password: postgres
      db_host: host.docker.internal
      db_port: 5432
    restart: unless-stopped
